### PR TITLE
intial changes

### PR DESCRIPTION
**Pull request by akiva-futter**

### CODE REVIEW

**Review by dorsimhon — APPROVED** [review]

**Review by tal-shachar1 — APPROVED** [review]

**Comment by akiva-futter** [comment]
@tal-shachar1 can you review the entire file for technical items? I noticed for example it only has 30 attributes and not 45, so not sure on the specifics if there is anything else that needs updating. 

Thanks

**Comment by tal-shachar1** [comment]
@dorsimhon 
**products** 
missing fields:
- product_type
- substitution_fk is missing, i see there is substitution_product_lead so check what is the right name 
- brand_code
- category_attibute_1
- category_attibute_2
- category_attibute_3
- customer_product_id
- width
- height

extra fields that not exist in the entities schema:
- alternative_designs
- images

I do see in the entities models some manipulations we are doing on the data besides the defined schemas, so it woth checking there as well.

**Routes**
cycles are not in the schema, but maybe we are getting it from stores & routes 
__LEGACY__/lib/entities/route_model.js -> getRoutesEntitiesByPKs

**Store type**
missing store_type_code and is_deleted?

**Stores**
missing:
- state_name
- address_line_2
- is_deleted
- audit_cycle_set
- and as @akiva-futter mentioned seems we are supporting 45 additional attributes, make sure with Josh thats correct

**Tasks**
- additional_attribute_1 - 4

maybe try to call the GET request for the problematic entities to check whats returns

**Comment by dorsimhon** [comment]
@akiva-futter 
updated with examples and with tal's comments (went over to see what the api actually returns rather than rely on our api documentation)

**Comment by tal-shachar1** [comment]
@dorsimhon  
on products substitution_product_lead is there twice.
additional attributes still say we can get only 30, have you checked that with Josh?

**Comment by dorsimhon** [comment]
> @dorsimhon on products substitution_product_lead is there twice. additional attributes still say we can get only 30, have you checked that with Josh?

* thanks, missed that
* I only changed one occurence of from 30 to 45, will change the others as well

**Review by tal-shachar1 — APPROVED** [review]

**Comment by akiva-futter** [comment]
@dorsimhon  if tal signed off go ahead and merge

**Pull request merged**
